//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicePosition
    {
        public int id { get; set; }
        public int abonement_id { get; set; }
        public int service_id { get; set; }
        public System.DateTime date_end { get; set; }
        public int count { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Service Service { get; set; }
    }
}
