//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewClients
    {
        public string surname { get; set; }
        public string name { get; set; }
        public int sex { get; set; }
        public string passp_num { get; set; }
        public string address { get; set; }
        public string telephone { get; set; }
        public int id { get; set; }
    }
}
