//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWorkWpfApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewContractWithAddPayment
    {
        public int coach_id { get; set; }
        public string title { get; set; }
        public double payment { get; set; }
        public Nullable<double> additional_payment { get; set; }
    }
}
